# Generated by Django 2.0 on 2018-04-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20180426_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='room.Room', verbose_name='면접실'),
        ),
    ]
