# Generated by Django 2.0 on 2018-04-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20180429_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.DateTimeField(verbose_name='끝나는 시간'),
        ),
        migrations.AlterField(
            model_name='time',
            name='interviewee',
            field=models.TextField(verbose_name='면접자'),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.DateTimeField(verbose_name='시작 시간'),
        ),
    ]
